# Generated by Django 6.1 on 2026-08-13 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_name', models.CharField(max_length=100)),
                ('teammate_name', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_email', models.EmailField(max_length=254, unique=True)),
                ('teammate_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('primary_mobile', models.CharField(max_length=15)),
                ('teammate_mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('team_name', models.CharField(max_length=100)),
                ('institution', models.CharField(max_length=200)),
                ('experience', models.TextField(blank=True, null=True)),
                ('payment_screenshot', models.ImageField(upload_to='screenshots/')),
                ('is_approved', models.BooleanField(default=False)),
                ('generated_username', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
