# Generated by Django 6.1 on 2026-08-15 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='classroom',
            field=models.CharField(blank=True, default='TBD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='debate_date',
            field=models.CharField(blank=True, default='TBD', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='debate_topic',
            field=models.CharField(blank=True, default='Waiting for Assignment...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='stance',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
