# Generated by Django 6.1 on 2026-08-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_teamregistration_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='debate_time',
            field=models.CharField(blank=True, default='TBD', max_length=100, null=True),
        ),
    ]
