# Generated by Django 6.1 on 2026-08-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_teamregistration_debate_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='add_merch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='primary_tshirt_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='teammate_tshirt_size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
