# Generated by Django 6.1 on 2026-08-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_teamregistration_add_merch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='referral_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teamregistration',
            name='payment_screenshot',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
