# Generated by Django 6.1 on 2026-08-24 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_teamregistration_referral_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='generated_password',
            field=models.CharField(blank=True, help_text='Plain-text password set at approval time. Read-only.', max_length=50, null=True),
        ),
    ]
