# Generated by Django 6.1 on 2026-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_teamregistration_generated_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregistration',
            name='txn_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
