# Generated by Django 6.1 on 2026-08-31 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_teamregistration_txn_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamregistration',
            name='primary_tshirt_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='teamregistration',
            name='teammate_tshirt_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
