# Generated by Django 6.1 on 2026-09-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_alter_teamregistration_primary_tshirt_size_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamregistration',
            old_name='debate_topic',
            new_name='round_1_topic',
        ),
        migrations.RemoveField(
            model_name='teamregistration',
            name='debate_time',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='round_2_topic',
            field=models.CharField(blank=True, default='Waiting for Assignment...', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='round_3_topic',
            field=models.CharField(blank=True, default='Waiting for Assignment...', max_length=500, null=True),
        ),
    ]
