# Generated by Django 6.1 on 2026-09-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0009_rename_debate_topic_teamregistration_round_1_topic_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamregistration',
            old_name='stance',
            new_name='round_1_stance',
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='round_2_stance',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='teamregistration',
            name='round_3_stance',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
